name: loggerx2
description: Colorful, neat and intuitive logger library, for creating a simple log messages with many urgency levels.
version: 1.0.0
repository: https://github.com/unix14/loggerx

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  ansi_styles: ^0.3.2+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
